name: tiktok_flutter_sdk
description: Flutter plugin enabling seamless integration with the official TikTok Mobile SDK
version: 0.0.1
homepage: https://www.linkedin.com/in/timophei-lemeshchenko-77a3a7b5

environment:
  sdk: ^3.7.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_lints: ^5.0.0

  pigeon: ^24.2.1

flutter:
  plugin:
    platforms:
      android:
        package: apps.another1dd.tiktok.sdk.tiktok_flutter_sdk
        pluginClass: TikTokFlutterSdkPlugin
      ios:
        pluginClass: TiktokFlutterSdkPlugin
